# Generated by Django 4.1.4 on 2022-12-15 14:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('cover', models.FileField(upload_to='cover_pic/')),
                ('github', models.URLField(max_length=100)),
                ('live_demo', models.URLField(blank=True, max_length=60, null=True)),
                ('tag', models.ManyToManyField(to='projects.tag')),
            ],
        ),
    ]
